### PR TITLE
Translate into Brazilian Portuguese

### PR DESCRIPTION
**Pull request by lucasmz-dev**
This pull request provides PT-BR translations for the app, and the Fastlane component, separate commits.
This PR does not make any changes to anything dealing with building the app to use them! You'll have to do that manually. I'd do it but I don't know how to mess with that.

### CODE REVIEW

**Comment by lucasmz-dev** [comment]
Also being tracked @ https://codeberg.org/lucasmz/translation-suggestions/issues/20

**Comment by mjaakko** [comment]
Thanks for the translation!

There were some hardcoded text values that were not included in strings.xml. If you could rebase your branch against master and add translations for those also, then we would have all texts translated

**Comment by lucasmz-dev** [comment]
@mjaakko OK, should be right now! I'm new to Git.

**Comment by lucasmz-dev** [comment]
Nice! From the builds created with GitHub it seems to work already out of the box, fully translated! It even works for Portuguese from Portugal instead of it using English. Nice.

**Pull request merged**
